@startuml
hide empty members
title Deployment Diagramm

folder "all-inkl hosting" {
node "E-Mail-Server" as Mail
}

folder "Feuerwehrhaus" {
folder "Schulungsraum" {
node "Fritz.Box" as FB
}
folder "Gerätehalle" {
node "Mini PC" as PC
node Drucker
node Bildschirm
}
}

FB -r- Mail : Internet
FB -r- PC : Ethernet
PC -d- Drucker : USB
PC -d- Bildschirm : HDMI
@enduml

